import type { VideoInsight, VaultItem, TrackedChannel, Watchlist, Project } from '@/types';

// ============================================================
// Rich mock data for development / demo
// ============================================================

export const MOCK_CHANNELS: TrackedChannel[] = [
  {
    id: 'ch-1',
    platform: 'YOUTUBE',
    handle: '@garyvee',
    display_name: 'Gary Vaynerchuk',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=garyvee',
    average_views: 850000,
    subscriber_count: 4200000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ch-2',
    platform: 'TIKTOK',
    handle: '@alexhormozi',
    display_name: 'Alex Hormozi',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hormozi',
    average_views: 1200000,
    subscriber_count: 8900000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ch-3',
    platform: 'INSTAGRAM',
    handle: '@mrBeast',
    display_name: 'MrBeast',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mrbeast',
    average_views: 45000000,
    subscriber_count: 230000000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ch-4',
    platform: 'YOUTUBE',
    handle: '@aidanmarcotte',
    display_name: 'Aidan Marcotte',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aidan',
    average_views: 120000,
    subscriber_count: 520000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ch-5',
    platform: 'TIKTOK',
    handle: '@justinwelsh',
    display_name: 'Justin Welsh',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=justin',
    average_views: 380000,
    subscriber_count: 1100000,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_WATCHLISTS: Watchlist[] = [
  {
    id: 'wl-1',
    user_id: 'user-1',
    name: 'Business Thought Leaders',
    created_at: new Date().toISOString(),
    channels: [MOCK_CHANNELS[0], MOCK_CHANNELS[1], MOCK_CHANNELS[4]],
  },
  {
    id: 'wl-2',
    user_id: 'user-1',
    name: 'Viral Entertainment',
    created_at: new Date().toISOString(),
    channels: [MOCK_CHANNELS[2]],
  },
  {
    id: 'wl-3',
    user_id: 'user-1',
    name: 'Creator Economy',
    created_at: new Date().toISOString(),
    channels: [MOCK_CHANNELS[3]],
  },
];

export const MOCK_VIDEOS: VideoInsight[] = [
  {
    id: 'vid-1',
    channel_id: 'ch-2',
    url: 'https://youtube.com/watch?v=example1',
    title: 'The ONLY Business Advice You Need in 2024',
    thumbnail_url: 'https://picsum.photos/seed/vid1/400/225',
    views: 8400000,
    likes: 342000,
    comments: 12400,
    duration_seconds: 58,
    outlier_score: 9.2,
    transcript: [
      { t: '00:00', text: "Stop doing what everyone else is doing. Here's why most people never build wealth." },
      { t: '00:05', text: "The number one mistake I see — people optimize for revenue instead of profit margin." },
      { t: '00:12', text: "Here's the framework that took my business from zero to $100M." },
      { t: '00:18', text: "First — you need to understand acquisition cost versus lifetime value." },
      { t: '00:25', text: "If you can't answer this in 10 seconds, you have a business problem." },
      { t: '00:32', text: "Second — most entrepreneurs are operators, not owners. Learn the difference." },
      { t: '00:40', text: "Third — and this is the one nobody talks about — leverage. Not financial leverage." },
      { t: '00:48', text: "If you want the full playbook, I break down all 12 principles in my book." },
      { t: '00:55', text: "Follow for daily business insights that actually move the needle." },
    ],
    visual_analysis: {
      visual_hook: 'Extreme close-up of subject pointing directly at camera with text overlay "MOST PEOPLE GET THIS WRONG" — creates immediate pattern interrupt and curiosity gap',
      pacing_cuts_per_sec: 3.2,
      broll_usage: 'Heavy use of income statements, business graphs, and stock footage of offices cut between talking head segments every 2-3 seconds',
      text_overlay_style: 'Bold white Helvetica captions with black drop shadow, key words highlighted in yellow, bottom-third placement, animated word-by-word reveal',
      camera_framing: 'Tight chest-up framing, slight Dutch angle, subject constantly moving and gesturing, 4K with shallow depth of field',
      color_grade: 'High contrast, slightly desaturated, warm skin tones, cinematic look with lifted blacks',
      screenshots: [],
      key_moments: [
        { timestamp: '0:00', description: 'Pattern-interrupt hook with extreme close-up and provocative text overlay' },
        { timestamp: '0:12', description: 'Social proof moment — "$100M" claim with animated counter graphic' },
        { timestamp: '0:32', description: 'Concept revelation with split-screen comparison graphic' },
        { timestamp: '0:48', description: 'Call-to-action with product thumbnail revealed' },
      ],
    },
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    channel: MOCK_CHANNELS[1],
    created_at: new Date().toISOString(),
    analyzed_at: new Date().toISOString(),
    language: 'en',
    country: 'US',
    tags: ['business', 'mindset', 'entrepreneur'],
  },
  {
    id: 'vid-2',
    channel_id: 'ch-1',
    url: 'https://youtube.com/watch?v=example2',
    title: 'Why You\'re Not Growing on Social Media (honest truth)',
    thumbnail_url: 'https://picsum.photos/seed/vid2/400/225',
    views: 2100000,
    likes: 98000,
    comments: 4300,
    duration_seconds: 62,
    outlier_score: 7.8,
    transcript: [
      { t: '00:00', text: "Nobody wants to hear this, but I'm going to say it anyway." },
      { t: '00:04', text: "Most people posting content are not creating — they're performing." },
      { t: '00:09', text: "And the algorithm can tell the difference. Your audience definitely can." },
      { t: '00:15', text: "I grew my following to 20 million by doing the complete opposite of what gurus teach." },
      { t: '00:23', text: "Stop chasing trends. Start building a point of view." },
      { t: '00:29', text: "Here are three things I changed in my content that shifted everything." },
      { t: '00:35', text: "One — I stopped using hooks. I started with the actual story." },
      { t: '00:43', text: "Two — I made my content uncomfortable for me to post. That\'s how you know it\'s real." },
      { t: '00:51', text: "Three — I posted every single day for 365 days, even when I hated it." },
      { t: '00:57', text: "Authenticity is the only content strategy that compounds over time." },
    ],
    visual_analysis: {
      visual_hook: 'Unedited, raw footage aesthetic — subject filmed on phone in car, deliberately lo-fi to signal authenticity and create contrast with polished content',
      pacing_cuts_per_sec: 1.8,
      broll_usage: 'Minimal B-roll — mostly talking head with occasional social media analytics screenshots and follower count animations',
      text_overlay_style: 'Casual, hand-written style font in coral/orange, appearing organically rather than animated, positioned dynamically around frame',
      camera_framing: 'Slightly shaky handheld, medium shot, subject looking away from camera at moments — feels like a private conversation',
      color_grade: 'Warm, slightly washed out, high exposure — feels like a FaceTime call rather than produced content',
      screenshots: [],
      key_moments: [
        { timestamp: '0:00', description: 'Disarming hook — "Nobody wants to hear this" creates anticipation' },
        { timestamp: '0:15', description: 'Social proof with specific number "20 million" shown with scrolling follower graphic' },
        { timestamp: '0:35', description: 'List format begins — numbered counter appears on screen' },
      ],
    },
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    channel: MOCK_CHANNELS[0],
    created_at: new Date().toISOString(),
    analyzed_at: new Date().toISOString(),
    language: 'en',
    country: 'US',
    tags: ['social-media', 'growth', 'authenticity'],
  },
  {
    id: 'vid-3',
    channel_id: 'ch-4',
    url: 'https://youtube.com/watch?v=example3',
    title: 'I Made $47K Last Month Selling Digital Products (Full Breakdown)',
    thumbnail_url: 'https://picsum.photos/seed/vid3/400/225',
    views: 680000,
    likes: 31000,
    comments: 2800,
    duration_seconds: 55,
    outlier_score: 6.4,
    transcript: [
      { t: '00:00', text: "Last month I made $47,000 selling digital products. Let me show you every dollar." },
      { t: '00:06', text: "This is my Gumroad dashboard. $31K from my notion templates." },
      { t: '00:14', text: "Another $12K from my course on content creation systems." },
      { t: '00:20', text: "And $4K from affiliate commissions. All while working 4 hours a day." },
      { t: '00:27', text: "Here\'s the exact system I used to build these products without any following." },
      { t: '00:34', text: "Step one: validate before you build. I spent 2 weeks DMing 100 people." },
      { t: '00:42', text: "Step two: build a minimum viable product in one weekend." },
      { t: '00:49', text: "Step three: launch to your email list, even if it\'s tiny." },
    ],
    visual_analysis: {
      visual_hook: 'Screen recording of actual earnings dashboard shown in first 3 seconds — extreme specificity ($47K not "6 figures") builds immediate credibility',
      pacing_cuts_per_sec: 2.1,
      broll_usage: 'Majority screen recordings with cursor highlighting specific numbers, alternating with talking head every 8-10 seconds',
      text_overlay_style: 'Clean minimal captions in white on dark overlay bar, dollar amounts highlighted in green — financial dashboard aesthetic',
      camera_framing: 'Picture-in-picture layout: screen recording main frame with small talking head circle in corner — maximizes information density',
      color_grade: 'Natural daylight, slightly cool tones, clean background — signals credibility and transparency',
      screenshots: [],
      key_moments: [
        { timestamp: '0:00', description: 'Earnings dashboard reveal — specific number shown within first 2 seconds' },
        { timestamp: '0:06', description: 'Breakdown by revenue stream — chart animates in' },
        { timestamp: '0:34', description: 'Step-by-step framework begins — numbered list with progress indicator' },
      ],
    },
    published_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    channel: MOCK_CHANNELS[3],
    created_at: new Date().toISOString(),
    analyzed_at: new Date().toISOString(),
    language: 'en',
    country: 'CA',
    tags: ['digital-products', 'income', 'solopreneur'],
  },
  {
    id: 'vid-4',
    channel_id: 'ch-5',
    url: 'https://tiktok.com/@justinwelsh/video/example4',
    title: 'The Solopreneur Stack That Replaced My $500K Agency',
    thumbnail_url: 'https://picsum.photos/seed/vid4/400/225',
    views: 3800000,
    likes: 187000,
    comments: 8900,
    duration_seconds: 48,
    outlier_score: 8.7,
    transcript: [
      { t: '00:00', text: "I shut down my 7-figure agency and replaced it with this." },
      { t: '00:04', text: "12 tools. 4 hours per day. $500K per year as a solopreneur." },
      { t: '00:09', text: "Tool 1: Notion — my entire business operates from one workspace." },
      { t: '00:14', text: "Tool 2: ConvertKit — 150K subscribers, $200K in email revenue alone." },
      { t: '00:21', text: "Tool 3: Loom — I replaced 90% of my meetings with 5-minute video updates." },
      { t: '00:27', text: "Tool 4: Gumroad — sells my products while I sleep. Literally." },
      { t: '00:33', text: "The other 8 tools are in my free Notion template — link in bio." },
      { t: '00:40', text: "Drop a 🔥 if you want me to do a deep dive on any of these." },
    ],
    visual_analysis: {
      visual_hook: 'Bold text-only intro "I SHUT DOWN MY 7-FIGURE AGENCY" over black screen — no face, no frills, pure curiosity hook that filters for business audience',
      pacing_cuts_per_sec: 2.8,
      broll_usage: 'Tool UI screenshots displayed full-screen for 2-3 seconds each, overlaid with earnings stats and usage metrics',
      text_overlay_style: 'High-contrast numbered list format, tool logos displayed alongside text, consistent font system throughout — looks like a premium presentation',
      camera_framing: 'Screen-share dominant with talking head in small overlay bubble, switches to face-cam for emotional moments',
      color_grade: 'Dark/night mode aesthetic matching the tools being shown — cohesive visual theme reinforces "digital-first" brand',
      screenshots: [],
      key_moments: [
        { timestamp: '0:00', description: 'Text-only hook creates curiosity without showing face' },
        { timestamp: '0:04', description: 'Specific numbers create credibility framework in 4 seconds' },
        { timestamp: '0:33', description: 'Lead magnet CTA woven naturally into content flow' },
      ],
    },
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    channel: MOCK_CHANNELS[4],
    created_at: new Date().toISOString(),
    analyzed_at: new Date().toISOString(),
    language: 'en',
    country: 'US',
    tags: ['tools', 'solopreneur', 'productivity'],
  },
];

export const MOCK_VAULT_ITEMS: VaultItem[] = [
  {
    id: 'vault-1',
    user_id: 'user-1',
    type: 'HOOK',
    content: 'Stop doing what everyone else is doing. Here\'s why most people never [achieve X].',
    tags: ['pattern-interrupt', 'contrarian', 'business'],
    source_video_id: 'vid-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vault-2',
    user_id: 'user-1',
    type: 'HOOK',
    content: 'I made $[specific amount] last [time period]. Let me show you every dollar.',
    tags: ['income-proof', 'transparency', 'specificity'],
    source_video_id: 'vid-3',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vault-3',
    user_id: 'user-1',
    type: 'HOOK',
    content: 'Nobody wants to hear this, but I\'m going to say it anyway.',
    tags: ['contrarian', 'emotional', 'authenticity'],
    source_video_id: 'vid-2',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vault-4',
    user_id: 'user-1',
    type: 'STYLE',
    content: 'Earnings dashboard reveal: Show the actual tool/dashboard in first 3 seconds. Use specific numbers (not "6 figures" — use "$47,293"). Highlight key metric in green. Creates immediate credibility and specificity.',
    tags: ['income-proof', 'screen-recording', 'credibility'],
    source_video_id: 'vid-3',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vault-5',
    user_id: 'user-1',
    type: 'STYLE',
    content: 'Numbered list format: Show a large number on screen as you introduce each point. Use bold, high-contrast typography. Keep each point under 8 seconds. Add visual element (icon, screenshot) for each item.',
    tags: ['list-format', 'education', 'high-retention'],
    source_video_id: 'vid-4',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vault-6',
    user_id: 'user-1',
    type: 'HOOK',
    content: 'I [took action] and replaced it with this. [Impressive number] results. [Small effort]. Here\'s how.',
    tags: ['replacement-hook', 'results', 'efficiency'],
    source_video_id: 'vid-4',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vault-7',
    user_id: 'user-1',
    type: 'STYLE',
    content: 'Raw authenticity aesthetic: Film on phone in car or casual setting. Slightly shaky, lo-fi look. No b-roll. Long pauses before key points. Makes audience feel like they\'re getting a private, unfiltered take.',
    tags: ['authenticity', 'raw', 'low-production'],
    source_video_id: 'vid-2',
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    user_id: 'user-1',
    name: 'Q1 Content Calendar',
    color: '#6366f1',
    created_at: new Date().toISOString(),
    items_count: 8,
  },
  {
    id: 'proj-2',
    user_id: 'user-1',
    name: 'Business Tips Series',
    color: '#10b981',
    created_at: new Date().toISOString(),
    items_count: 3,
  },
  {
    id: 'proj-3',
    user_id: 'user-1',
    name: 'Viral Research Archive',
    color: '#f59e0b',
    created_at: new Date().toISOString(),
    items_count: 14,
  },
];
